### ISSUE TITLE
get_video_length caught unexpected string instead of a duration in seconds

### ISSUE THREAD

**Issue by shuaiscott** [shuaiscott/edlstrip#7]
**Describe the bug**
get_video_length caught unexpected string instead of a duration in seconds

**To Reproduce**
1. Convert a file (probably file related issue)

**Expected behavior**
It should parse out the duration of the video

**Screenshots**
```
2020-12-22 23:18:00,254 - root - INFO - Read 10 lines from xxxxx 2020-12-17-1759.edl
Traceback (most recent call last):
  File "/usr/local/bin/edlstrip", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/edlstrip/__init__.py", line 181, in main
    end_timecode = to_timecode(get_video_length(args.video))
  File "/usr/local/lib/python3.7/dist-packages/edlstrip/__init__.py", line 81, in get_video_length
    length = float(result.stdout)
ValueError: could not convert string to float: b'[h264 @ 0x55dad57d1700] non-existing PPS 0 referenced\n    Last message repeated 1 times\n[h264 @ 0x55dad57d1700] decode_slice_header error\n[h264 @ 0x55dad57d1700] no frame!\n7262.859255\n'
```

**Comment by Torqu3Wr3nch** [comment]
Similar issue but different error message from ffprobe:
```
2021-10-05 03:29:02,362 - root - INFO - Read 8 lines from edlFileName.edl
Traceback (most recent call last):
File "/usr/bin/edlstrip", line 8, in <module>
sys.exit(main())
File "/usr/lib/python3.9/site-packages/edlstrip/init.py", line 213, in main
end_timecode = to_timecode(get_video_length(args.video))
File "/usr/lib/python3.9/site-packages/edlstrip/init.py", line 93, in get_video_length
length = float(result.stdout)
ValueError: could not convert string to float: b'[mpeg2video @ zzzzz ] Invalid frame dimensions 0x0.\n3599.478111\n'
```
